# Generated by Django 2.2.3 on 2019-07-18 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('favorite_animal', models.CharField(blank=True, max_length=50)),
                ('favorite_hobby', models.CharField(blank=True, max_length=50)),
                ('favorite_movie', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
